### ISSUE TITLE
Split Taxonomic table in taxonomic levels

### ISSUE THREAD

**Issue by nselem** [ccm-bioinfo/cambda2023#5]
Run Reads and assembly tables and construct OTU Tables at Phylum, Class, Order, Family, genera levels.
Share tsv in the Github Repo, clearly available for everybody to use them

**Comment by inuzm** [comment]
- [The tables generated with Reads](https://github.com/ccm-bioinfo/cambda2023/tree/main/Variable_Selection/data/reads)
- [The tables generated with Assembly](https://github.com/ccm-bioinfo/cambda2023/tree/main/Variable_Selection/data/assembly)

All tables are linked in the [main page](https://github.com/ccm-bioinfo/cambda2023).
